CITY_LIST = [
    'Вінниця',
    'Дніпро',
    'Донецьк',
    'Житомир',
    'Запоріжжя',
    'Івано-Франківськ',
    'Київ',
    'Кропивницький',
    'Луганськ',
    'Луцьк',
    'Львів',
    'Миколаїв',
    'Одеса',
    'Полтава',
    'Рівне',
    'Севастополь',
    'Суми',
    'Тернопіль',
    'Ужгород',
    'Харків',
    'Херсон',
    'Хмельницький',
    'Черкаси',
    'Чернівці',
    'Чернігів'
]

LANG_LEVELS = [
    'Beginner (A1)',
    'Elementary (A2)',
    'Pre-Intermediate (B1)',
    'Intermediate (B2)',
    'Upper-Intermediate (C1)',
    'Advanced (C2)',
    'Fluent (C2)',
    'Native Speaker'
]

EXP_LEVEL = [
    'Без досвіду',
    'Менше 1 року',
    '1 рік',
]

SPECIALISATIONS = [
    'Python',
    'JavaScript',
    'Java',
    'C++',
    'C#',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'TypeScript',
    'Go (Golang)',
    'Rust',
    'MATLAB',
    'Perl',
    'Dart',
    'R',
    'Scala',
    'Lua',
    'Bash (Shell)',
    'HTML',
    'CSS',
    'Objective-C',
    'Haskell',
    'Groovy',
    'Elixir',
    'Clojure',
    'VHDL',
    'COBOL',
    'Delphi',
    'Pascal',
    '1C',
    'QA (Quality Assurance)',
    'Manual QA',
    'Automation QA',
    'Design / UI/UX',
    '2D/3D Artist / Illustrator',
    'Project Manager',
    'Product Manager',
    'Architect / CTO (Chief Technology Officer)',
    'DevOps',
    'Business Analyst',
    'Data Science',
    'Data Analyst',
    'Sysadmin (System Administrator)',
    'Gamedev / Unity',
    'SQL / DBA (Database Administrator)',
    'Security',
    'Data Engineer',
    'Scrum Master / Agile Coach'
]
